module-template: ! 'module MODULE_NAME where

'
extensions:
  TemplateHaskell: true
  OverloadedStrings: true
  QuasiQuotes: true
  TypeFamilies: true
  MultiParamTypeClasses: true
environment: ghc-7.8-stable-14.09
cabal-file: project.cabal
version: 1
extra-packages: ''
ghc-args: []
excluded-modules: []
